# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    ".gitleaksignore",
    ".gitignore",
    ".secrets.baseline",
    ".markdownlintignore",
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "renovate.json",
    ".markdownlint.json",
    ".vale.ini",
    ".releaserc.yml",
    ".cspell.json",
    ".jscpd.json",
    ".mega-linter.yml",
  ".luacheckrc",
  ".luarc.json"
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/workflows/*"
precedence = "override"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".github/ISSUE_TEMPLATE/*",
    ".github/PULL_REQUEST_TEMPLATE.md"
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "CHANGELOG.md",
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "meta/vale-styles/config/vocabularies/Custom/accept.txt"
]
precedence = "override"
SPDX-FileCopyrightText = "2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"
